### ISSUE TITLE
PyPi Package doesn't include user-agents.txt

### ISSUE THREAD

**Issue by bnichs** [lvxhnat/pyetf-scraper#8]
**Describe the bug**
On a fresh install of the package, user-agents.txt is missing: 

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/ben/.cache/pypoetry/virtualenvs/finance-ItsvA0nu-py3.11/lib/python3.11/site-packages/pyetfdb_scraper/data/user-agents.txt'
```

If you download the src directly from pypi: https://files.pythonhosted.org/packages/33/4d/617eb1f807bc5ab4c9c2af13240facb55aed350325ee2b28d1457a3dcdf5/pyetfdb_scraper-0.2.tar.gz

You can see the file is not on the tarball and that the setup.py doesn't have the package_data line found here: https://github.com/lvxhnat/pyetfdb-scraper/blob/master/setup.py#L36

I'm not sure how the build system works but it seems that the build on pypi is out of date and missing commits like https://github.com/lvxhnat/pyetfdb-scraper/commit/88dcc0c6dc4b12f5c49a06788174d7a74b17e95d

**To Reproduce**
1. Do fresh install of package from pypi (not github) 
2. 
```from pyetfdb_scraper.etf import ETF,load_etfs
etf = ETF("IHAK")
print(etf.to_dict())
```

**Expected behavior**
Dictionary output

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu / Linux 6.6.22-060622-generic
 - Python 3.11.6

**Smartphone (please complete the following information):**
N/A

**Additional context**
Full traceback: 

```
Traceback (most recent call last):
  File "/home/ben/workplace/finance/./finnhib.py", line 20, in <module>
    etf = ETF("IHAK")
          ^^^^^^^^^^^
  File "/home/ben/.cache/pypoetry/virtualenvs/finance-ItsvA0nu-py3.11/lib/python3.11/site-packages/pyetfdb_scraper/etf.py", line 12, in __init__
    super().__init__(ticker, user_agent)
  File "/home/ben/.cache/pypoetry/virtualenvs/finance-ItsvA0nu-py3.11/lib/python3.11/site-packages/pyetfdb_scraper/etf_scraper.py", line 32, in __init__
    self.user_agents = load_user_agents()
                       ^^^^^^^^^^^^^^^^^^
  File "/home/ben/.cache/pypoetry/virtualenvs/finance-ItsvA0nu-py3.11/lib/python3.11/site-packages/pyetfdb_scraper/etf_scraper.py", line 129, in load_user_agents
    with open(path, "r") as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ben/.cache/pypoetry/virtualenvs/finance-ItsvA0nu-py3.11/lib/python3.11/site-packages/pyetfdb_scraper/data/user-agents.txt'
(8:42:48) ben@fralix:~/workplace/finance (master* ^ detached) (No VPN)    
(finance-py3.11) % poetry run python ./finnhib.py
Traceback (most recent call last):
  File "/home/ben/workplace/finance/./finnhib.py", line 20, in <module>
    etf = ETF("IHAK")
          ^^^^^^^^^^^
  File "/home/ben/.cache/pypoetry/virtualenvs/finance-ItsvA0nu-py3.11/lib/python3.11/site-packages/pyetfdb_scraper/etf.py", line 12, in __init__
    super().__init__(ticker, user_agent)
  File "/home/ben/.cache/pypoetry/virtualenvs/finance-ItsvA0nu-py3.11/lib/python3.11/site-packages/pyetfdb_scraper/etf_scraper.py", line 32, in __init__
    self.user_agents = load_user_agents()
                       ^^^^^^^^^^^^^^^^^^
  File "/home/ben/.cache/pypoetry/virtualenvs/finance-ItsvA0nu-py3.11/lib/python3.11/site-packages/pyetfdb_scraper/etf_scraper.py", line 129, in load_user_agents
    with open(path, "r") as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ben/.cache/pypoetry/virtualenvs/finance-ItsvA0nu-py3.11/lib/python3.11/site-packages/pyetfdb_scraper/data/user-agents.txt'
```

**Comment by bnichs** [comment]
Wondering if its as simple as adding `*txt` to https://github.com/lvxhnat/pyetfdb-scraper/blob/master/MANIFEST.in 

Made https://github.com/lvxhnat/pyetfdb-scraper/pull/9 for a quick fix if that seems right to maintainer.
